2022-03-21 00:31:38,003 - ERROR - Exception occured
Traceback (most recent call last):
  File "C:\Users\aisha\PycharmProjects\PriceBasket\main.py", line 82, in display_inventory
    cart_products = get_cart_products()
  File "C:\Users\aisha\PycharmProjects\PriceBasket\main.py", line 71, in get_cart_products
    with open('Cache/cart/cartProducts.pkl', 'rb') as in_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Cache/cart/cartProducts.pkl'
